### ISSUE TITLE
WooCommerce Settings

### ISSUE THREAD

**Issue by manticarodrigo** [appticles/pwa-theme-woocommerce#37]
I'm trying to recreate the demo with a self-hosted WP/WC installation. In the `public/index.html` file I've updated my endpoints like so: `API_CATEGORIES_URL: 'https://example.com/wp-json/wc/v2/products/categories/',` and added the consumer key/secret to the url params but the app is giving me various errors including `Unhandled Rejection (TypeError): Cannot read property '_currentElement' of null`.

What version of WooCommerce is this for, and how do I customize my endpoints to work for this PWA?

**Comment by manticarodrigo** [comment]
I found an explanation in the video on this page: https://wpmobilepack.com/blog/progressive-web-app-wordpress-woocommerce-reactjs/. Where can I find the PHP wrapper used for proxying the API?

**Comment by EkoAlex** [comment]
You can find the WordPress plugin associated with the PWA here: [https://wordpress.org/plugins/pwacommerce/](url)
