### ISSUE TITLE
Does it work with Dokan Multivendor?

### ISSUE THREAD

**Issue by streetlist** [appticles/pwa-theme-woocommerce#50]
Does it work with Dokan Multivendor?

**Comment by anghelalexandra** [comment]
No, it does not. It is implemented on top of the WooCommerce REST API endpoints that you can find in the official documentation (http://woocommerce.github.io/woocommerce-rest-api-docs/#introduction). The endpoints used right now are:

- list products
- list categories
- list reviews
- list product variations
