### ISSUE TITLE
Can you make this dokan compatible?

### ISSUE THREAD

**Issue by unisqu** [appticles/pwa-theme-woocommerce#54]
If it's dokan compatible, I'm sure a lot of people will buy including me.

**Comment by anghelalexandra** [comment]
I'm sorry, for the moment our priority is making this PWA compatible with the basic endpoints of the WooCommerce REST API. If you check our list of opened issues, you will see that this is the direction we're following.

However, we accept PRs that make sense for the functionality of the PWA. If you want to contribute on making it compatible with WooCommerce extensions / plugins, please open a pull request.
